### ISSUE TITLE
Can i generate job configs from exsiting jobs in my Controlm ? So I can use them to automate going forward.

### ISSUE THREAD

**Issue by TejjeT** [controlm/automation-api-community-solutions#128]

**Comment by nathanw9722** [comment]
Hi @TejjeT, you can use Automation API to GET the job definitions for any existing jobs. You can then use Automation API to DEPLOY those jobs after modifying them to the same environment or a different one. You can also automate these deployments with a tool such as Jenkins or Gitlab. You can find the documentation for [Automation API's latest monthly release here](https://docs.bmc.com/docs/automation-api/monthly/control-m-automation-api-home-1116950269.html).
